# Generated by Django 5.2.12 on 2026-03-04 22:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_description', models.TextField()),
                ('template', models.CharField(choices=[('Classic', 'Classic'), ('Modern', 'Modern'), ('Minimal', 'Minimal')], default='Classic', max_length=20)),
                ('tone', models.CharField(choices=[('Formal', 'Formal'), ('Balanced', 'Balanced'), ('Casual', 'Casual')], default='Balanced', max_length=20)),
                ('humanization_level', models.PositiveSmallIntegerField(default=3)),
                ('imperfection_mode', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResumeResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.JSONField(default=dict)),
                ('ats_score', models.PositiveSmallIntegerField(default=0)),
                ('human_score', models.PositiveSmallIntegerField(default=0)),
                ('keyword_match', models.PositiveSmallIntegerField(default=0)),
                ('pdf_url', models.URLField(blank=True)),
                ('docx_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='generator.resumejob')),
            ],
        ),
    ]
